### PR TITLE
move debug to function

### PR DESCRIPTION
**Pull request by lvenier**
have a single function for debug.
might have slightly change the behavior but more shiny code.

I let you make comment.

Rgds

### CODE REVIEW

**Comment by lvenier** [comment]
I agree with your approch and would have tend to go that way.
I was going "baby step" to avoid regression and make small moves. :smile: 

I fully agree about the ability to dynamically turn off and on debug. That would make sense to have that flipping mechanism on the nodes : debug producer, debug consumer... but that would be great then to have the debug visible on the node-red flow as an output. you can then debug and decide if you want it on console or not.

I you agree I can check how to implement it.

**Comment by lvenier** [comment]
@peterprib : I have updated the PR with your proposal. Make some adjustement but can be changed. I also add the debug into the node configuration screen. waiting for your opinion.

Also fixed an issue on redeploying breaking the producer (due to on old kafka-node issue I guess based on your comment).

I have tested producer and consumerGroup on my local envirronement. Seems to be working fine.

Waiting for your feedback :smiley_cat:

**Comment by peterprib** [comment]
Just thought of a better way to implement that could be used generically across node-red contributions with possible greater benefits such as include logging to console.  Will set up and test.

**Comment by lvenier** [comment]
I think the best would be the debug to output to "msg.payload" then people can send them whenver they want. Dont you think ?

**Comment by peterprib** [comment]
Just testing a new node-red contribute which will give a logging node plus allow to be embedded into other node such as this.  Which I could extend to turn on logging messages in and out of any node.  Done this type of thing before with my queue manager contribution.

**Comment by lvenier** [comment]
oki doki
Let me know if you want me tom make some testing.

**Comment by peterprib** [comment]
have implemented debug by completely new contribution so can use in other contributions

**Pull request closed without merging**
